default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV["pool"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>
  socket: <%= ENV["socket"] %>

development:
  <<: *default
  database: demo_development

production:
  adapter: mysql2
  encoding: utf8
  database: demo_production
  username: <%= ENV["user_name"] %>
  password: <%= ENV["pass_word"] %>
  host: <%= ENV["host"] %>
