default: &default
  adapter: mysql2

development:
  <<: *default
  database: <%= ENV["database_dev"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>
  host: <%= ENV["host_dev"] %>

production:
  <<: *default
  database: <%= ENV["database"] %>
  username: <%= ENV["user_name"] %>
  password: <%= ENV["pass_word"] %>
  host: <%= ENV["host"] %>
