# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6088f5d829f05eadb2d0f86944f4667420c372b5442d33cf534c9b58d9b9b1e91cc3213f57b4a74ca48c5504eb07632371f967b807e9058f40ea31441802e628

test:
  secret_key_base: 8a033fd5f361803368a5e406ef90adaef1afd0eb0455c32885c2efbca759400000bba7a034d8352dd4ceb45e99b8ef39b547f1afa69067625a6fe35adaa27ff1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 106bf73ab9071e8aba5f440f7bb5db07f003ca0a8bed76363bb03fede785f525bdb8ad05b968062ecec54ff27a833beab21a4d7ec15a54a3fb17cc0ed6dabb0a
